### ISSUE TITLE
Installation Warnings different then that outlined in documentation

### ISSUE THREAD

**Issue by finteractive** [codingdesigner/Survival-Kit#6]
Works great, but I get a different error then what's outlined in the documentation. And looking at it that error might include the solution to suppressing those error messages on install?

I'm running:

sass-3.2.0.alpha.277
compass-0.12.2

--Warning Output--

WARNING on line 26 of /_work/BLG-DEE_ux_planning/_website/blg/sass/partials/03-extend/_typography.scss: "%allcaps" failed to @extend ".caps".
  The selector ".caps" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .caps !optional" if the extend should be able to fail.

WARNING on line 35 of /_work/BLG-DEE_ux_planning/_website/blg/sass/partials/03-extend/_typography.scss: "%smallcaps" failed to @extend ".caps".
  The selector ".caps" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .caps !optional" if the extend should be able to fail.

   create blg/css/style.css 
   create blg/css/survivalkit/drupal7.css 
WARNING on line 55 of /Users/aidanfoster/.rvm/gems/ruby-1.9.2-p318@blg/gems/survivalkit-0.3.4/stylesheets/survivalkit/survival_kit/_survival-kit.sass:
This selector doesn't have any properties and will not be rendered.
WARNING on line 17 of /Users/aidanfoster/.rvm/gems/ruby-1.9.2-p318@blg/gems/survivalkit-0.3.4/stylesheets/survivalkit/extend/_sticky-footer.sass: "%row-expand" failed to @extend ".row".
  The selector ".row" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .row !optional" if the extend should be able to fail.

WARNING on line 26 of /_work/BLG-DEE_ux_planning/_website/blg/sass/partials/03-extend/_typography.scss: "%allcaps" failed to @extend ".caps".
  The selector ".caps" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .caps !optional" if the extend should be able to fail.

WARNING on line 35 of /_work/BLG-DEE_ux_planning/_website/blg/sass/partials/03-extend/_typography.scss: "%smallcaps" failed to @extend ".caps".
  The selector ".caps" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .caps !optional" if the extend should be able to fail.

WARNING on line 112 of /Users/aidanfoster/.rvm/gems/ruby-1.9.2-p318@blg/gems/survivalkit-0.3.4/stylesheets/survivalkit/survival_kit/_survival-kit.sass: "body.survival-kit div.element .example .markup + .show-source" failed to @extend ".mono".
  The selector ".mono" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .mono !optional" if the extend should be able to fail.

**Comment by codingdesigner** [comment]
Thanks for pointing this out. I'm working on a rewrite now that's nearly ready. I think I found all these errors, but I'll double-check before pushing.

**Comment by drejohnson** [comment]
I get this error when creating project:

error survivalkit/sass/style.scss (Line 24 of survivalkit/sass/partials/01-variables/_colors.scss: Function color-schemer is missing argument $base-color.)

**Comment by codingdesigner** [comment]
Sass 3.2 introduced more strict rules for passing in default variables. I'm working on Survival Kit 1.0 and have this fixed in the beta. I recommend giving that a try. 

https://rubygems.org/gems/survivalkit/versions/1.0.beta.1

If not, let me know here and I'll try to find time for a service release.

**Comment by drejohnson** [comment]
Still gets error

error sass/style.scss (Line 58 of sass/partials/04-defaults/_common.scss: Undefined mixin 'underline-links'.)

**Comment by codingdesigner** [comment]
That mixin was renamed to be more accurate. (border-links) There's enough new or changed in version 1 that you should create a fresh project. I recommended 1 beta since I thought you were starting something new. If you're working on an existing project you may have a few other issues. 

Either way I'm going to work on a service release soon. Should be able to have it ready this week.

**Comment by drejohnson** [comment]
Thanks. I'm just testing this out, so I'll start fresh.

**Comment by drejohnson** [comment]
I'm trying to start fresh:

compass create webproject -r survivalkit -u survivalkit --javascripts-dir js --css-dir css

But now I get this error

Errno::ENOENT on line ["78"] of /Users/schapman/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.13.alpha.0/lib/compass/installers/base.rb: No such file or directory - /Users/schapman/.rvm/gems/ruby-1.9.3-p194/gems/survivalkit-1.0.beta.1/lib/../templates/project/../shared/style.scss
Run with --trace to see the full backtrace

**Comment by codingdesigner** [comment]
A-ha. Thanks for finding this. I had some shared assets that weren't packaged in the gem. That's fixed now in beta 2. 
`sudo gem install survivalkit --pre`

**Comment by drejohnson** [comment]
That worked perfectly. Thanks
